# Generated by Django 2.1.1 on 2018-09-12 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dName', models.CharField(default='', max_length=200, verbose_name='主域名')),
                ('ctime', models.DateTimeField(default=datetime.datetime(2018, 9, 12, 10, 31, 17, 901363), verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dName', models.CharField(default='', max_length=200, verbose_name='主域名')),
                ('sdName', models.CharField(default='', max_length=200, verbose_name='子域名')),
                ('ip', models.CharField(default='', max_length=500, verbose_name='解析地址')),
                ('ctime', models.DateTimeField(default=datetime.datetime(2018, 9, 12, 10, 31, 17, 901723), verbose_name='创建时间')),
            ],
        ),
    ]
